[project]
name = "rulesys"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.0.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.9.0",
    "shap>=0.52.0",
    "xgboost>=3.3.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pytest>=9.1.1",
]
